# config.yaml
parsers:
  headers:
    User-Agent: "Mozilla/5.0 (compatible; MyParser/1.0)"

  MMCS:
    base_url: "https://mmcs.sfedu.ru"
    endpoints:
      general_info:
        path: "/toabitur"
        selectors:
          info: "div.article-content"
          contacts: "div.yjsquare_in address"
      history:
        path: "/2014-12-10-12-02-39/greatpatrioticwar"
        selectors:
          history: "div.newsitem_text"
      masters:
        path: "/%D0%BC%D0%B0%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0"
        selectors:
          masters: "div.news_item_a"

  SFEDU:
    base_url: "https://sfedu.ru"
    endpoints:
      general_info:
        path: "/www/stat_pages22.show?p=UNI/N11897/P"
        selectors:
          info: "div#ideologiya1"
      history:
        path: "/www/stat_pages22.show?p=HIS/main/M"
        selectors:
          history: "div.content"
      education:
        path: "/www/stat_pages22.show?p=EDU/N12080/P"
        selectors:
          education: "article.left_side_column"
      mobility:
        path: "/www/stat_pages22.show?p=NAM/main/M"
        selectors:
          mobility: "article.left_col"